version: '2'
services:
  mongo:
    image: mongo
  keystone:
    build: 
      context: .
      dockerfile: node.Dockerfile
    image: las-keystone-node
    links: 
      - mongo
    ports:
      - "3000:3000"
    volumes:
      - ./keystone.js:/usr/src/app/keystone.js
      - ./models:/usr/src/app/models
      - ./routes:/usr/src/app/routes
      - ./updates:/usr/src/app/updates
